# Generated by Django 4.2.1 on 2023-05-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthorStory",
        ),
    ]
