# Generated by Django 4.2.1 on 2023-06-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_chaptersotry_typestory_longstory_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chaptersotry",
            name="image",
        ),
        migrations.AddField(
            model_name="chaptersotry",
            name="isPublish",
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="longstory",
            name="isPublish",
            field=models.BooleanField(default=0, verbose_name=False),
            preserve_default=False,
        ),
    ]
