# Generated by Django 4.2.1 on 2023-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_user_alter_comment_author_alter_longstory_author_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
