# Generated by Django 4.2.1 on 2023-06-11 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0009_alter_longstory_author_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="longstory",
            name="author_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("isPublish", models.BooleanField(verbose_name=False)),
                ("type", models.CharField(max_length=100)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Story",
            },
        ),
        migrations.AlterField(
            model_name="chaptersotry",
            name="story_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.story"
            ),
        ),
    ]
